# site properties and page defaults
title: visualization and image data management
subtitle: 
description: VIM (Visualization and Image Data Management) aims to connect research labs, university hospitals, and open source partners. Its mission is to provide a platform for research and educational exchange and to join efforts in developing and standardizing data formats, platforms and interfaces for analyzing and communicating biomedical imaging data.
header: images/background.jpg
footer: images/background.jpg
header-dark: true
footer-dark: true
data-dark: true

# site social media and other links
links:
  email: krueger@g.harvard.edu
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: vis-image-management
  twitter: vis-image-management
  youtube: vis-image-management

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  - scope:
      type: "orgas"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each orga
  orgas:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
